# config.toml
baseURL = 'https://nixinfra.com/'
languageCode = "en"
defaultContentLanguage = "en"
title = "SysNetHub"
theme = 'hugo-theme-relearn'


[params]
  # Subtitle = "A Blog about network and system infrastructures"
  [[params.themeVariant]]
    identifier = 'github'
    name = 'Light Mode'
  [[params.themeVariant]]
    identifier = 'monokai'
    name = 'Dark Mode'

  alwaysopen = false
  custom_css = ["https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css", 
                "css/custom.css"]

  [params.imageEffects]
    # quy trinh upload anh: crop 16:9 -> resize max width 1000px -> nen -> upload
    # cu phap markdown chen anh:  ![text-anh](images/ten-anh)
    lazy = true
    lightbox = true
    border = true

[menu]
  [[menu.sidebar]]
  name = "MORE"
  identifier = "more"
  url = "#"
  weight = 35
  class = "menu-separator"



[taxonomies]
  category = 'categories'
  mycustomtag = 'mycustomtags'
  tag = "tags"
  series = "series"

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.highlight]
    style = "monokai"         # Đã giữ phong cách code block bạn chọn
    noClasses = false         # Quan trọng cho cú pháp Relearn
    codeFences = true
    guessSyntax = true

  [markup.goldmark]
    [markup.goldmark.render]    
      unsafe = true              # dung de render HTML inline
