# config.toml
baseURL = "https://nixinfra.com/"
languageCode = "en-us"
title = "JUVENTUS"
theme = "terminal"

[params]
  description = "BE A HERO, BE A WARRIOR"
  Subtitle = "A blog about System and Network"

[menu]
  [[menu.main]]
    name = "LINUX"
    url = "/categories/linux/"
    weight = 10
  [[menu.main]]
    name = "WINDOWS"
    url = "/categories/windows/"
    weight = 20
  [[menu.main]]
    name = "CISCO"
    url = "/categories/cisco/"
    weight = 30
  [[menu.main]]
    name = "SHORT"
    url = "/categories/short/"
    weight = 40

[taxonomies]
  category = "categories"
  tag = "tags"

[markup]
  [markup.highlight]
    style = "monokai"
