# config.toml
baseURL = 'https://nixinfra.com/'
languageCode = "en"
defaultContentLanguage = "en"
title = "SysNetHub"
theme = 'hugo-theme-relearn'

[params]
  # Subtitle = "A Blog about network and system infrastructures"
  themeVariant = "relearn-light"
  themeVariants = ["relearn-light", "relearn-dark", "relearn-auto"]
  alwaysopen = false
  custom_css = ["https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css","css/custom.css"]

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[markup]
  [markup.highlight]
    style = "monokai"         # Đã giữ phong cách code block bạn chọn
    noClasses = false         # Quan trọng cho cú pháp Relearn
    codeFences = true
    guessSyntax = true

  [markup.goldmark]
    [markup.goldmark.render]    
      unsafe = true              # dung de render HTML inline
