# config.toml
baseURL = 'https://nixinfra.com/'
languageCode = "en"
defaultContentLanguage = "en"
title = "SysNetHub"
theme = 'hugo-theme-relearn'

[params]
  # Subtitle = "A Blog about network and system infrastructures"
  themeVariant = "relearn-light"
  themeVariants = ["relearn-light", "relearn-dark", "relearn-auto"]
  alwaysopen = false
  custom_css = ["https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css","css/custom.css"]

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[markup]
  [markup.highlight]
    style = "monokai"         # Đã giữ phong cách code block bạn chọn
    noClasses = false         # Quan trọng cho cú pháp Relearn
    codeFences = true
    guessSyntax = true

  [markup.goldmark]
    [markup.goldmark.render]    
      unsafe = true              # dung de render HTML inline

[Immersive content redacted for brevity.]
```eof

### 2. File `static/css/custom.css` (Thêm Đường Kẻ Ngang)

Bạn vui lòng **thêm đoạn code dưới đây vào CUỐI file `static/css/custom.css`** hiện tại của bạn (giữ nguyên code logo và code sửa lỗi font mobile):

```css:Custom CSS (Thêm Đường Kẻ Ngang):static/css/custom.css
/* -------------------------------------------------------------------
 * BỔ SUNG: TẠO ĐƯỜNG PHÂN CÁCH (Divider) TRONG SIDEBAR
 * -------------------------------------------------------------------
 */

/* Nhắm mục tiêu vào mục menu có ID 'divider' (Sử dụng ID này làm selector CSS) */
li#divider {
    /* Đảm bảo nó chiếm đủ không gian */
    height: 1px;
    
    /* Thêm khoảng đệm trên và dưới để tạo khoảng trống */
    margin: 15px 0;
    padding: 0;
    
    /* Thiết lập đường kẻ ngang */
    border-top: 1px solid rgba(255, 255, 255, 0.2); /* Màu trắng mờ (Màu này hợp với nền tối của sidebar) */
    
    /* Bỏ text 'DIVIDER' */
    visibility: hidden; 
}
/* Đối với các mục menu bên dưới đường kẻ ngang, thêm margin trên */
li#divider + li {
    margin-top: 15px;
}
```eof

### Các bước cuối cùng:

1.  **Lưu file `config.toml`** (đã thay thế toàn bộ).
2.  **Lưu file `static/css/custom.css`** (đã thêm đoạn CSS Divider).
3.  **Chạy Hugo Build/Server** để xem kết quả!
