# config.toml
baseURL = 'https://nixinfra.com/'
languageCode = "en"
defaultContentLanguage = "en"
title = "SysNetHub"
theme = 'hugo-theme-relearn'


[params]
  # Subtitle = "A Blog about network and system infrastructures"
  [[params.themeVariant]]
    identifier = 'github'
    name = 'Light Mode'
  [[params.themeVariant]]
    identifier = 'monokai'
    name = 'Dark Mode'

  alwaysopen = false
  custom_css = ["https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css", 
                "css/custom.css"]
  custom_js = ["js/separator.js"]
  showVisitedLinks = true

  [[params.sidebarmenus]]
    type = 'menu'
    identifier = 'main'
    main = false
    disableTitle = true

  [[params.sidebarmenus]]
    type = 'custom'
    identifier = 'more-title'
    title = 'MORE'
    main = true
    disableTitle = true
    elements = []

  [[params.sidebarmenus]]
    type = 'menu'
    identifier = 'utilities'
    main = false
    disableTitle = true


[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.highlight]
    style = "monokai"         # Đã giữ phong cách code block bạn chọn
    noClasses = false         # Quan trọng cho cú pháp Relearn
    codeFences = true
    guessSyntax = true

  [markup.goldmark]
    [markup.goldmark.render]    
      unsafe = true              # dung de render HTML inline


